# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PersonalAssistant(object):
    def setupUi(self, PersonalAssistant):
        PersonalAssistant.setObjectName("PersonalAssistant")
        PersonalAssistant.resize(941, 1120)
        PersonalAssistant.setMouseTracking(False)
        PersonalAssistant.setLayoutDirection(QtCore.Qt.LeftToRight)
        PersonalAssistant.setAutoFillBackground(False)
        PersonalAssistant.setAnimated(True)
        PersonalAssistant.setDocumentMode(False)
        PersonalAssistant.setDockNestingEnabled(False)
        PersonalAssistant.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        PersonalAssistant.setUnifiedTitleAndToolBarOnMac(False)
        PersonalAssistant.setStyleSheet(
            "padding: 20px; background-color: #FFF8E6; spacing: 10")

        self.centralwidget = QtWidgets.QWidget(PersonalAssistant)
        self.centralwidget.setObjectName("centralwidget")

        #линия
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 630, 941, 1))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_4.setStyleSheet(
            "background-color: #000;")

        #описание
        self.descriptionScrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.descriptionScrollArea.setGeometry(QtCore.QRect(35, 635, 865, 165))
        self.descriptionScrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.descriptionScrollArea.setWidgetResizable(True)
        self.descriptionScrollArea.setObjectName("descriptionScrollArea")
        self.descriptionScrollArea.setStyleSheet(
            "border: none;")
        self.descriptionWidgetContents = QtWidgets.QWidget()
        self.descriptionWidgetContents.setGeometry(QtCore.QRect(0, 0, 865, 180))
        self.descriptionWidgetContents.setObjectName("descriptionWidgetContents")
        self.descriptionLabel = QtWidgets.QLabel(self.descriptionWidgetContents)
        self.descriptionLabel.setWordWrap(True)
        self.descriptionLabel.setMinimumSize(800, 100)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.descriptionLabel.setTextFormat(QtCore.Qt.RichText)
        self.descriptionLabel.setStyleSheet(
            "border: none; font-size: 30px; font-family: Arial, sans-serif;")
        self.descriptionLayout = QtWidgets.QVBoxLayout(self.descriptionWidgetContents)
        self.descriptionLayout.addWidget(self.descriptionLabel)
        self.descriptionLayout.setContentsMargins(0, 0, 0, 0)
        self.descriptionWidgetContents.setLayout(self.descriptionLayout)
        self.descriptionScrollArea.setWidget(self.descriptionWidgetContents)

        #поле для общения
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(40, 110, 860, 400))
        self.scrollArea.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet(
            "background-color: #E7DDC7; margin: 20px 0px; border-radius: 50px;")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 820, 360))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.vertical_layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_7)
        self.vertical_layout.setAlignment(QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_7)

        #табл
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setGeometry(QtCore.QRect(40, 800, 860, 350))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_2.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.scrollArea_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollArea_2.setAcceptDrops(False)
        self.scrollArea_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scrollArea_2.setLineWidth(1)
        self.scrollArea_2.setMidLineWidth(0)
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea_2.setWidgetResizable(False)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollArea_2.setStyleSheet(
            "border: none;")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 800, 300))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 521))
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.setStyleSheet(
            "text-align: center; padding: auto;")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 775, 250))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_55.setMinimumSize(QtCore.QSize(0, 50))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 3, 1, 1, 1)
        self.label_55.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-right: none; border-left: none; border-bottom: none; padding: auto; text-align: center;")
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_56.setMinimumSize(QtCore.QSize(0, 50))
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 4, 0, 1, 1)
        self.label_56.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-left: none;")
        self.label_57 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_57.setMinimumSize(QtCore.QSize(0, 50))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 1, 0, 1, 1)
        self.label_57.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-left: none; border-bottom: none;")
        self.label_58 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_58.setMinimumSize(QtCore.QSize(0, 50))
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 1, 1, 1, 1)
        self.label_58.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-right: none; border-left: none; border-bottom: none;")
        self.label_59 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_59.setMinimumSize(QtCore.QSize(0, 50))
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.gridLayout_6.addWidget(self.label_59, 0, 1, 1, 1)
        self.label_59.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-right: none; border-bottom: none; border-left: none;")
        self.label_60 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_60.setMinimumSize(QtCore.QSize(0, 50))
        self.label_60.setAlignment(QtCore.Qt.AlignCenter)
        self.label_60.setObjectName("label_60")
        self.gridLayout_6.addWidget(self.label_60, 3, 0, 1, 1)
        self.label_60.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-left: none; border-bottom: none;")
        self.label_61 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_61.setMinimumSize(QtCore.QSize(0, 50))
        self.label_61.setScaledContents(False)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setWordWrap(False)
        self.label_61.setOpenExternalLinks(False)
        self.label_61.setObjectName("label_61")
        self.gridLayout_6.addWidget(self.label_61, 0, 0, 1, 1)
        self.label_61.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-left: none; border-bottom: none; text-align: center;")
        self.label_62 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_62.setMinimumSize(QtCore.QSize(0, 50))
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.gridLayout_6.addWidget(self.label_62, 2, 0, 1, 1)
        self.label_62.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-left: none; border-bottom: none;")
        self.label_63 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_63.setMinimumSize(QtCore.QSize(0, 50))
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.gridLayout_6.addWidget(self.label_63, 4, 1, 1, 1)
        self.label_63.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-right: none; border-left: none;")
        self.label_64 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_64.setMinimumSize(QtCore.QSize(0, 50))
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.gridLayout_6.addWidget(self.label_64, 2, 1, 1, 1)
        self.label_64.setStyleSheet(
            "font-size:10pt; border-color: #000; border-width: 1px; border-style: solid; border-right: none; border-left: none; border-bottom: none;")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)

        #Поле ввода
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 520, 941, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_10 = QtWidgets.QFrame(self.horizontalLayoutWidget_4)
        self.frame_10.setMaximumSize(QtCore.QSize(725, 80))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setStyleSheet(
            "background-color: #E7DDC7; color: #000; font-size: 20px; padding: 0px 75px 0px 20px; border-radius: 35px; border-style: solid; border-width: 3px; border-color: #0D6D50;")
        self.frame_10.setObjectName("frame_10")
        self.textEdit_input = QtWidgets.QTextEdit(self.frame_10)
        self.textEdit_input.setGeometry(QtCore.QRect(0, 0, 725, 80))
        self.textEdit_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.textEdit_input.setObjectName("textEdit_input")

        #кнопка отправки
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_4.setGeometry(QtCore.QRect(645, 0, 80, 80))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setText("")
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setAutoRepeatDelay(0)
        self.pushButton_4.setAutoRepeatInterval(100)
        self.pushButton_4.setAutoDefault(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setFlat(False)
        self.pushButton_4.clicked.connect(self.add_text_to_scroll_area)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Send.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setProperty("1", icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet(
            "background-color: rgba(255, 255, 255, 0); z-index: 99; border: none;")
        self.label_3 = QtWidgets.QLabel(self.frame_10)
        self.label_3.setGeometry(QtCore.QRect(653, 10, 60, 60))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setTabletTracking(False)
        self.label_3.setAcceptDrops(False)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Send.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_3.setStyleSheet(
            "padding: 0 0 0 5px; border-radius: 30px; border: none;")
        self.textEdit_input.raise_()
        self.label_3.raise_()
        self.pushButton_4.raise_()
        self.horizontalLayout_4.addWidget(self.frame_10)

        #кнопка голоса
        self.frame_14 = QtWidgets.QFrame(self.horizontalLayoutWidget_4)
        self.frame_14.setEnabled(True)
        self.frame_14.setMaximumSize(QtCore.QSize(70, 70))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_14.setStyleSheet(
            "border-radius: 35px; border: none;")
        self.toolButton_9 = QtWidgets.QToolButton(self.frame_14)
        self.toolButton_9.setEnabled(True)
        self.toolButton_9.setGeometry(QtCore.QRect(0, 0, 70, 70))
        self.toolButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton_9.setMouseTracking(True)
        self.toolButton_9.setTabletTracking(False)
        self.toolButton_9.setAcceptDrops(False)
        self.toolButton_9.setText("")
        self.toolButton_9.setStyleSheet(
            "background-color: rgba(255, 255, 255, 0);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Frame 136.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_9.setProperty("2", icon1)
        self.toolButton_9.setObjectName("toolButton_9")
        self.label_2 = QtWidgets.QLabel(self.frame_14)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 70, 70))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Frame 136.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.label_2.setStyleSheet(
            "padding: 0;")
        self.toolButton_9.raise_()
        self.horizontalLayout_4.addWidget(self.frame_14)

        #перед табл
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 790, 936, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.setStyleSheet(
            "font-size: 10pt; padding: 0;")

        #шапка
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(40, 20, 860, 90))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_44.sizePolicy().hasHeightForWidth())
        self.label_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setAutoFillBackground(False)
        self.label_44.setStyleSheet(
            "background-color: #0D6D50; color: white; font-size: 30px; border-radius: 45px;")
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        PersonalAssistant.setCentralWidget(self.centralwidget)
        self.retranslateUi(PersonalAssistant)
        QtCore.QMetaObject.connectSlotsByName(PersonalAssistant)

        self.toolButton_9.toggled.connect(self.toggle_voice_button_border)
        self.toolButton_9.setCheckable(True)

    def retranslateUi(self, PersonalAssistant):
        _translate = QtCore.QCoreApplication.translate
        PersonalAssistant.setWindowTitle(_translate("PersonalAssistant", "MainWindow"))
        self.descriptionLabel.setText(_translate("PersonalAssistant",
                                         "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                         "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                         "p, li { white-space: pre-wrap; }\n"
                                         "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
                                         "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">\n"
                                         "<span style=\" font-size:10pt;\">Электронный персональный голосовой ассистент ВятГУ – цифровая программа, выступающая в виде голосового помощника, призванная кардинально упростить навигацию и поиск различного рода учебной информации для студентов абитуриентов и преподавателей ВятГУ, в информационной среде университета а именно на официальном сайте ВятГУ. Голосовой помощник призван стать незаменимым инструментом в цифровой среде университета, предоставляя быстрый доступ к любой интересующей вас информации.<br />Забудьте о долгом поиске нужных разделов на сайте. Теперь достаточно лишь озвучить свой запрос, и ассистент мгновенно предоставит вам требуемые сведения. Хотите узнать расписание занятий? Нужна актуальная информация о преподавательском составе или контактные данные кафедр? Желаете ознакомиться с последними новостями университета или условиями поступления? Наш голосовой помощник справится с любой из этих задач, предоставляя точные и своевременные ответы.<br />Особое внимание уделено абитуриентам. Понимание структуры университета, выбор специальности — это зачастую непростая задача. Голосовой ассистент станет вашим надежным советчиком, предоставляя подробную информацию об институтах, факультетах и направлениях подготовки, помогая сделать осознанный и взвешенный выбор. Внедрение такого помощника также является важным шагом на пути к повышению доступности образовательных ресурсов, особенно для студентов с ограниченными возможностями, делая университет по-настоящему инклюзивной средой.</span></p></body></html>"))
        # Подпись табл
        self.label.setText(_translate("PersonalAssistant", "C помощью помощника вы можете узнать"))
        # Шапка
        self.label_44.setText(_translate("PersonalAssistant", "Персональный ассистент ВятГУ"))
        # Табл
        self.label_55.setText(_translate("PersonalAssistant", "Расписание"))
        self.label_56.setText(_translate("PersonalAssistant", "Информацию про колледж"))
        self.label_57.setText(_translate("PersonalAssistant", "Институты, факультеты и кафедры"))
        self.label_58.setText(_translate("PersonalAssistant", "Информацию про поступление"))
        self.label_59.setText(_translate("PersonalAssistant", "Информацию про преподавателей"))
        self.label_60.setText(_translate("PersonalAssistant", "Информацию про корпуса"))
        self.label_61.setText(_translate("PersonalAssistant", "Контакты"))
        self.label_62.setText(_translate("PersonalAssistant", "Новости"))
        self.label_63.setText(_translate("PersonalAssistant", "Нормативные акты"))
        self.label_64.setText(_translate("PersonalAssistant", "Календарный учебный график"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PersonalAssistant = QtWidgets.QMainWindow()
    ui = Ui_PersonalAssistant()
    ui.setupUi(PersonalAssistant)
    PersonalAssistant.show()
    sys.exit(app.exec_())